Xueqiu_crawler_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('crawler.api.urls', namespace='api')),
    url(r'^crawler/', include('crawler.urls', namespace='crawler')),
    url(r'^polls/', include('polls.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^course/', include('courses.urls')),
    url(r'^students/', include('students.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

crawler/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views


router = routers.DefaultRouter()
router.register('portfolio', views.PortfolioViewSet)
#router.register('positions_change_list', views.Positions_change_ListView)
#router.register('accumulated_position_list', views.Accumulated_position_ListView)

urlpatterns = [
    url(r'^positions_change/$',
        views.Positions_change_ListView.as_view(), name='positions_change_list'),
    #url(r'^positions_change/(?P<pk>\d+)/$',
    #    views.Positions_change_DetailView.as_view(), name='positions_change_detail'),
    url(r'^accumulated_position/$',
        views.Accumulated_position_ListView.as_view(), name='accumulated_position_list'),
    #url(r'^accumulated_position/(?P<pk>\d+)/$',
    #    views.Accumulated_position_DetailView.as_view(), name='accumulated_position_detail'),
    url('^positions_change/(?P<portfolio>\d+)$', views.Positions_change_List.as_view()),
    url('^accumulated_position/(?P<portfolio>\d+)$', views.Accumulated_position_List.as_view()),
    url(r'^', include(router.urls)),
]

crawler/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^(?P<slug>[-\w]+)$', views.portfolio_detail, name='detail'),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

courses/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.auth.models import User
from .fields import OrderField
from django.template.loader import render_to_string
from django.utils.safestring import mark_safe


class Subject(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title


class Course(models.Model):
    owner = models.ForeignKey(User, related_name='courses_created')
    subject = models.ForeignKey(Subject, related_name='courses')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    overview = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    students = models.ManyToManyField(User,
                                      related_name='courses_enrolled',
                                      blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title


class Module(models.Model):
    course = models.ForeignKey(Course, related_name='modules')
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    order = OrderField(blank=True, for_fields=['course']) #OrderField的用法

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '{}. {}'.format(self.order, self.title)


class Content(models.Model):
    module = models.ForeignKey(Module, related_name='contents')
    order = OrderField(blank=True, for_fields=['module']) #OrderField的用法
    content_type = models.ForeignKey(ContentType,
                                     limit_choices_to={'model__in':('text',
                                                                    'video',
                                                                    'image',
                                                                    'file')}) #ForeignKey, limit_choices_to的用法
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id') #GenericForeignKey的用法

    class Meta:
        ordering = ['order']


class ItemBase(models.Model):
    owner = models.ForeignKey(User, related_name='%(class)s_related')
    title = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string('courses/content/{}.html'.format(self._meta.model_name), {'item': self}) #render_to_string的用法


class Text(ItemBase):
    content = models.TextField()


class File(ItemBase):
    file = models.FileField(upload_to='files') #FileField的用法


class Image(ItemBase):
    file = models.FileField(upload_to='images')


class Video(ItemBase):
    url = models.CharField(max_length=250)

crawler/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.core.urlresolvers import reverse


class Portfolio(models.Model):
    STAUTS_CHOICE = (
        ('pending', 'Pending'),
        ('done', 'Done'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    created = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STAUTS_CHOICE, default='pending')
    num = models.IntegerField(default=0)
    name = models.CharField(max_length=250)
    followers = models.CharField(max_length=250)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title) #slugify的用法
        super(Portfolio, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('crawler:detail', args=[self.slug])


class Positions_change(models.Model):
    portfolio = models.ForeignKey(Portfolio, related_name='changes')
    time = models.DateTimeField()
    name = models.CharField(max_length=80)
    code = models.CharField(max_length=20)
    detail = models.CharField(max_length=80)

    class Meta:
        ordering = ('-time',)

    def __str__(self):
        return '{} changed: {}, followed by {}'.format(self.name, self.detail, self.portfolio)


class Accumulated_position(models.Model):
    portfolio = models.ForeignKey(Portfolio, related_name='accum')
    stock = models.CharField(max_length=20)
    percent = models.DecimalField(max_digits=10, decimal_places=2)
    people = models.PositiveIntegerField(db_index=True, default=0)

    class Meta:
        ordering = ('percent',)

    def __str__(self):
        return '{} totol percentage: {}, followed by {}'.format(self.stock, self.percent, self.portfolio)

crawler/forms.py
from django import forms
from .models import Portfolio


class CrawlerForm(forms.ModelForm):

    class Meta:
        model = Portfolio
        fields = ('title',) #表单的字段

crawler/api/views.py
from rest_framework import generics
from ..models import Positions_change, Accumulated_position, Portfolio
from .serializers import Positions_change_Serializer, Accumulated_position_Serializer, Portfolio_Serializer
from rest_framework import viewsets
from rest_framework.decorators import detail_route
from rest_framework.authentication import BasicAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.pagination import PageNumberPagination

class Positions_change_ListView(generics.ListAPIView):
   queryset = Positions_change.objects.all()
   serializer_class = Positions_change_Serializer


"""
class Positions_change_DetailView(generics.RetrieveAPIView):
   queryset = Positions_change.objects.all()
   serializer_class = Positions_change_Serializer
"""


class Accumulated_position_ListView(generics.ListAPIView):
   queryset = Accumulated_position.objects.all()
   serializer_class = Accumulated_position_Serializer


"""
class Accumulated_position_DetailView(generics.RetrieveAPIView):
   queryset = Accumulated_position.objects.all()
   serializer_class = Accumulated_position_Serializer


class PortfolioViewSet(viewsets.ReadOnlyModelViewSet):
   queryset = Portfolio.objects.all()
   serializer_class = Portfolio_Serializer
"""


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 1
    page_size_query_param = 'page_size'
    max_page_size = 4


class PortfolioViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Portfolio.objects.all()
    serializer_class = Portfolio_Serializer
    pagination_class = LargeResultsSetPagination

    @detail_route(methods=['get'],
            serializer_class=Portfolio_Serializer,
            authentication_classes=[BasicAuthentication],
            permission_classes=[IsAuthenticated])

    def contents(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)


class Positions_change_List(generics.ListAPIView):
    serializer_class = Positions_change_Serializer

    def get_queryset(self):
        portfolio =Portfolio.objects.filter(slug = self.kwargs['portfolio']).first().id
        return Positions_change.objects.filter(portfolio=portfolio)


class Accumulated_position_List(generics.ListAPIView):
    serializer_class = Accumulated_position_Serializer

    def get_queryset(self):
        portfolio =Portfolio.objects.filter(slug = self.kwargs['portfolio']).first().id
        return Accumulated_position.objects.filter(portfolio=portfolio)

crawler/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CrawlerForm
from .models import Portfolio, Accumulated_position, Positions_change
from django.contrib import messages
from .login import login
import requests
from bs4 import BeautifulSoup

agent = 'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
headers = {
    'User-Agent': agent,
    'Host': "xueqiu.com",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Encoding": "gzip, deflate, sdch, br",
    "Accept-Language": "zh-CN,zh;q=0.8,zh-TW;q=0.6",
    "Connection": "keep-alive"
}
session = requests.session()


telephone = '******'
password  = '******'

def dashboard(request):
    portfolios = Portfolio.objects.all()
    form = CrawlerForm(data=request.POST or None)
    if form.is_valid():
        new_item = form.save(commit=False)
        url = 'https://xueqiu.com/'+new_item.title
        headers = login(telephone, password)
        data = session.get(url, headers=headers).text
        #try:
        soup = BeautifulSoup(data, "lxml")
        followers = soup.find('li', class_="gender_info" )
        try:
            followers = followers.find_next_siblings("li")[0]
            followers = followers.contents[0]
            slug = soup.find('a', class_="setRemark" )['data-user-id']
        except:
            followers = "无可奉告"
            slug = new_item.title
        if not Portfolio.objects.filter(slug=slug):
            new_item.name = soup.title.string[0:len(soup.title.string)-5]
            new_item.followers = followers
            new_item.slug= slug
            new_item.save()
            messages.success(request, 'Portfolio added successfully')
            return redirect('/crawler')
        else:
            messages.error(request, 'Portfolio already in the database')
        #except:
            #messages.error(request, 'Portfolio does not exist')
    return render(request, 'crawler/dashboard.html', {'form': form,
                                                      'portfolios': portfolios})


def portfolio_detail(request, slug):
    portfolio = get_object_or_404(Portfolio, slug = slug) #get_object_or_404的用法
    accums = Accumulated_position.objects.filter(portfolio=portfolio)
    positions = Positions_change.objects.filter(portfolio=portfolio)
    return render(request, 'crawler/crawler/detail.html', {'portfolio': portfolio, 'accums':accums, 'positions':positions}) #render的用法

crawler/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>程健的几个小作品</title>
    <link rel="icon" type="image/jpg" href="/static/images/icon.jpg" />
    <!-- Bootstrap Core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <!-- Theme CSS -->
    <link href="static/css/freelancer.min.css" type="text/css" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="static/vendor/font-awesome/css/Lato.css" rel="stylesheet" type="text/css">
    <link href="static/vendor/font-awesome/css/Montserrat.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">
<div id="skipnav"><a href="#maincontent">Skip to main content</a></div>

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only"> 导航 </span> 目录 <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">程健的几个小作品</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#portfolio">个人作品</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#about">关于</a>
                    </li>
                    <li class="page-scroll">
                        <a href="#contact">联系</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                <div class="col-lg-12">
                    <img class="img-responsive" src="static/img/profile.png" alt="">
                    <div class="intro-text">
                        <h1 class="name">程健的几个小作品</h1>
                        <hr class="star-light">
                        <span class="skills">这里有我在业余时间完成的一些作品，实现了一些小小的功能</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Portfolio Grid Section -->
    <section id="portfolio">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>个人作品</h2>
                    <hr class="star-primary">
                </div>
            </div>
              <div class="row">
                <div class="col-sm-4 portfolio-item">
                    <a href="{% url "crawler:dashboard" %}" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-play fa-2x">挖雪球</i>
                            </div>
                        </div>
                        <img src="static/img/portfolio/xueqiu.png" class="img-responsive" alt="Game controller">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="{% url "polls:index" %}" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-play fa-2x">Polls调查</i>
                            </div>
                        </div>
                        <img src="static/img/portfolio/polls.png" class="img-responsive" alt="Safe">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="{% url "course_list" %}" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-play fa-2x">在线教育</i>
                            </div>
                        </div>
                        <img src="static/img/portfolio/edu.png" class="img-responsive" alt="Submarine">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>挖雪球的功能</h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                  <img src="static/img/portfolio/xueqiu_function.jpeg" class="img-responsive" alt="Safe">
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <a href="{% url "crawler:dashboard" %}" class="btn btn-lg btn-outline">
                        <i class="fa fa-play"></i> 立即体验
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>邮件联系</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <form name="sentMessage" id="contactForm" novalidate>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label for="name">姓名</label>
                                <input type="text" class="form-control" placeholder="姓名" id="name" required data-validation-required-message="Please enter your name.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label for="email">邮箱</label>
                                <input type="email" class="form-control" placeholder="邮箱地址" id="email" required data-validation-required-message="Please enter your email address.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label for="phone">电话号码</label>
                                <input type="tel" class="form-control" placeholder="电话号码" id="phone" required data-validation-required-message="Please enter your phone number.">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label for="message">消息</label>
                                <textarea rows="5" class="form-control" placeholder="消息" id="message" required data-validation-required-message="Please enter a message."></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-lg">发送</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                        <ul class="list-inline navbar-right">
                          <li>
                              <a class="btn-social btn-outline weixin"><span class="sr-only">Weixin</span><i class="fa fa-fw fa-weixin"><img class="qrcode" src="static/img/Wechat_code.jpeg"></i></a>
                          </li>
                          <li>
                              <a href="https://www.github.com/newer027" class="btn-social btn-outline"><span class="sr-only">Github</span><i class="fa fa-fw fa-github"></i></a>
                          </li>
                          <li>
                              <a href="http://weibo.com/u/1274947427" class="btn-social btn-outline"><span class="sr-only">Weibo</span><i class="fa fa-fw fa-weibo"></i></a>
                          </li>
                          <li>
                              <a href="https://twitter.com/122521200" class="btn-social btn-outline"><span class="sr-only">Twitter</span><i class="fa fa-fw fa-twitter"></i></a>
                          </li>
                          <li>
                              <a href="https://www.linkedin.com/in/jacob-lean/" class="btn-social btn-outline"><span class="sr-only">Linked In</span><i class="fa fa-fw fa-linkedin"></i></a>
                          </li>
                        </ul>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                      *^_^*  感谢您的访问 *^_^*
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>

    <!-- jQuery -->
    <script type="text/javascript" src="/static/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script type="text/javascript" src="/static/js/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script type="text/javascript" src="/static/js/jqBootstrapValidation.js"></script>
    <script type="text/javascript" src="/static/js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script type="text/javascript" src="/static/js/freelancer.min.js"></script>
</body>

</html>